### ISSUE TITLE
Getting error when I run your code with an image file saying memory is gone

### ISSUE THREAD

**Issue by akshayacharya97** [GSNCodes/Instance_Segmentation_Mask_RCNN#4]
Hi, I have cloned your repo adn I have given the path to my respective image and executed it. However, I am getting the following errror
```
Traceback (most recent call last):
  File "mask.py", line 165, in <module>
    my_config)
  File "mask.py", line 36, in prepare_mrcnn_model
    model = modellib.MaskRCNN(mode="inference", model_dir=model_path, config=my_config)
  File "/home/ubuntu/segmentation/Instance_Segmentation_Mask_RCNN/mrcnn/model.py", line 1837, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/ubuntu/segmentation/Instance_Segmentation_Mask_RCNN/mrcnn/model.py", line 1901, in build
    stage5=True, train_bn=config.TRAIN_BN)
  File "/home/ubuntu/segmentation/Instance_Segmentation_Mask_RCNN/mrcnn/model.py", line 197, in resnet_graph
    x = identity_block(x, 3, [256, 256, 1024], stage=4, block=chr(98 + i), train_bn=train_bn)
  File "/home/ubuntu/segmentation/Instance_Segmentation_Mask_RCNN/mrcnn/model.py", line 117, in identity_block
    name=conv_name_base + '2b', use_bias=use_bias)(x)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 862, in _infer_output_signature
    self._maybe_build(inputs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2710, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 205, in build
    dtype=self.dtype)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 639, in add_weight
    caching_device=caching_device)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 810, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 142, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2618, in default_variable_creator
    shape=shape)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1585, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1712, in _init_from_args
    initial_value = initial_value()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/initializers/initializers_v2.py", line 410, in __call__
    shape, dtype=_get_dtype(dtype), **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops_v2.py", line 600, in __call__
    return self._random_generator.random_uniform(shape, -limit, limit, dtype)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops_v2.py", line 1082, in random_uniform
    shape=shape, minval=minval, maxval=maxval, dtype=dtype, seed=self.seed)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/random_ops.py", line 308, in random_uniform
    result = math_ops.add(result * (maxval - minval), minval, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1164, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1496, in _mul_dispatch
    return multiply(x, y, name=name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 518, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6068, in mul
    _ops.raise_from_not_ok_status(e, name)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,3,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Mul]
```
What do i do?

**Comment by GSNCodes** [comment]
Hi @akshayacharya97 !

You are getting an Out Of Memory error. It might be because of your GPU capacity. You could maybe try running inference in Google Colab with the same test image and see if that's working.

Also, if you do have enough memory,  make sure that it is not being used by any other program.

Let me know if this works :)

**Comment by GSNCodes** [comment]
I hope this issue is resolved.
Closing the issue due to inactivity.
